name: API Test

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - labeled
      - synchronize
      
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check if the label is 'api-test'
        run: echo "Label is ${{ github.event.label.name }}"
        if: ${{ github.event.label.name == 'api-test' }}
        
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Install dependencies
        run: pip install requests

      - name: Install dependencies
        run: pip install pyyaml

      - name: Run API test
        run: python test/test_api.py
